name: Freedom Financial Partners
favicon: null
layout_spectrum: 0.8313471162691712
typography_spectrum: 0.35206210031174123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2557360837236047
  lightness: 0.9071085609029979
  saturation: 0.5916779241524637
  rhythmicContrast: 0.9266356099396944
purpose: []
